
# Preface {-}

What is the extent of poverty and why? Why some population groups or regions are more likely to be poor than others? The answers to these questions are decisive for our intitutional order in that they shed light on the state and trends of capital issues such as fairness and injustice. Accurate and precise measurement is crucial because high uncertainty numbs and deviates our attention, actions and judgements from the chief goal which is the eradication of poverty. 

The international consensus is that poverty is multidimensional and that it should be measured taking into account the substantive aspects of people's necessities of life. However, the answer about the extent and nature of multidimensional poverty is contested and unsatisfactory. The perils of bad measurement are many. Societies are likely to waste resources and time based on poor evidence and data. Academics and goverments have the responsibility to produce good measures not only to replicate their findings and advance evidence but to reduce the negative effects of noisy measurements upon the policymaking process. 

There are several theoretical and methodological reasons impeding the production of uncontested poverty measures. There are many theories of human needs that debate the substantive aspects that humans must have to live with dignity. Furthermore, even if these theoretical discussions find a satisfactory solution, several practical obstacles require to be addressed for the successful development of poverty scales. These challenges occur at different stages of the production of an index. Poverty is a human invention that needs to be tractable using multivariate data to accurately capture its substantive aspects. This challenge often results in a noise-magnifying process in which researchers make several assumptions about the relevant set of necessities to include in an index, the thresholds to identify deprivation, the weighting scheme to reflect the importance of different needs, the way in which the poor and not poor are identified. Furthermore, all these assumptions are constrained by the available data, which is seldom collected with the a priori idea of measuring poverty. Invariably, researchers have to make decisions and presumptions which are influenced by biases (plus random error). 

Poverty measurement requires a cogent framework to mitigate confirmation biases by putting our assumptions to scrutiny. A framework to help researchers and goverments to resolve some empirical issues in poverty measurement such as: Is it sensible to aggregate an ex ante list of indicators into an index? Are there any indicators that do not work as expected? Does the scale orders well the population from low to high living standards? Is this ordering consistent across samples and groups? is differential weighting useful at all? Does the theoretical dimensions seem to hold given the data? Is the population split optimal in that it leads to meaninful groups? 

This book focuses on one of the key problems in contemporary poverty measurement- the lack of a framework to assess the assumptions underlying a multidimensional scale. The book provides a series of tools to fight against prejudice, misconception and error in poverty measurement. It draws upon measurement theory, with a history of 100 years of continuous development, to help researchers to avoid producing noise-magnifying indices. This book provides a series of falsifiable principles and criteria to assess whether our poverty rates are just a reflection of noise mining and unlikely to replicate. Poverty research has overlooked the developments in other fields and although sometimes some aspects of measurement theory are recovered its use is partial, inaccurate and unsystematic. In 2016, the World Bank Commission [-@Bank2017] on Global Poverty, headed by Sir Anthony Atkinson, has put into perspective the different challenges in multidimensional poverty measurement and set out 21 recommendations. Recommendation 4 of the World Bank report acknowledges the need of validating poverty indices. But it does not propose how to do so. This is understandable because one of the one of the main difficulties in contemporary poverty measurement is the absence of an explicit discussion about how to check all these assumptions.

The most common practice still consists in using ad hoc or idiosyncratic methods to assess some arbitrary properties of a multidimensional scale. To date very few exercises in multidimensional poverty measurement rely on an explicit statistical framework to put under scrutiny the assumptions of an index. @Guio2012 and @Guio2017 is perhaps the most comprehensive implementation that draws upon the experience from the Poverty and Social Exclusion (PSE) and Peter Townsend's outstanding work. However, the methods its application using software are not widely available for the community interested in measuring poverty. One of the problems is that there are several books on poverty measurement but there is none exclusively dedicated to the topic of empirical examination of poverty indices. Most of the books focus on the production of an index but devote little attention to the issue of validation. This reflects the fact that poverty research has followed the path of many other fields. There have been other disciplines in a similar struggle. Educational testing, psychological measurement, sociology but also in the natural sciences biology and medicine often face measurement challenges. However, many of these disciplines have taken measurement very seriously and have adopted a series of practices and principles that reduce uncertainty about the attribute they measure. These areas rely on the seminal work of [@Spearman1904] on correlation and latent variables that resulted in the development measurement theory and methods with more than 100 years of history and continuous development from the classical works on factor analysis [@Thorndike1969;@Thurstone1947;@Lazardfeld1968;@Cudeck2012], passing through the development of the principles of validity and reliability [@Guttman1945,Novick1967,Novick1967,Brennan2006], then through the modern framework of the latent variable approach [@Bartholomew1987;@Muthen2007;@Skrondal2007;@Kvalheim2012] and finally to the classic handbooks that show how all these principles and method constitute sound measurement framework [@Allen2001;@Brennan2006;@McDonald2013;@Streiner2015;@Michell2015]. This framework has been so widely accepted that has lead to the adoption of standards in some academic journals so that authors provide a more objective judgement about the quality of their measurement. 

The book draws upon measurement theory and methods that have proven to be useful in many other fields, to illustrate how a unified framework can be for empirical examination of multidimensional poverty measures. It translates key concepts and principles of measurement theory and methods and illustrate is implementation using both simulated and real data examples. The book is intended for applied researchers and students. Most of the examples rely on **R-software** and **Mplus** [@Muthen2012;@RCT2018]. 

The principal goal of this book is to help researchers, students and technicians at the government to understand the importance of the principles of measurement theory in poverty measurement and to enhance their skills for empirical analyses of poverty indices. After studying the book readers should be able to:

* Understand why is important to have falsifiable measures in poverty research
* Identify the difference between a method of aggregation and a methodology for empirical examination
* Appreciate the relevance of measurement theory to examine poverty indices but also to understand its limitations
* Understand how the principles of reliability and validity are a necessary condition for a minimum quality of measurement
* Implement analysis of reliability and validity in widely used software
* Interpret the results of the analysis critically 
* Appreciate the role measurement invariance and scale equating for the comparison of poverty indices 
* Implement basic analysis of measurement invariance and equating in poverty measurement
* Identify appropriate and inappropriate uses of the method and principles of measurement theory

The book is organised as follows. The first chapter introduces the links between the problems in poverty measurement and the principles of measurement theory. The chapter starts by overweening some of the key debates and consensuses in the literature. It puts emphasis on the challenges and assumptions that take place when measuring poverty and the possible response from measurement theory. The second chapter introduces, discusses and translates the concept of reliability to poverty measurement. It uses simulated data and real data to illustrate the consequences of violating reliability and shows how reliability is deeply connected with some axioms in poverty measurement. The third chapter presents the concept of validity and relates the different types of validity to the checks that can be done in poverty research. Chapter four concerns with the topic of comparability in poverty measurement. It shows how the principle of measurement invariance is central for making valid comparisons across groups and periods. Chapter five continues with the topic of comparability but focuses on the issue of making seemingly incomparable scales comparable. It draws on the principles and method of scale linking and equating. 

This book would have been possible without the support...



